# Generated by Django 2.1.2 on 2018-10-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalsetter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('inspire_id', models.IntegerField(verbose_name='inspire_id')),
            ],
        ),
    ]
